### ISSUE TITLE
[BUG] The `set-output` command is deprecated

### ISSUE THREAD

**Issue by DavidePastore** [Cyb3r-Jak3/html5validator-action-experimental#3]
**Describe the bug**
A warning appears when trying to launch this action. You can read more about it, [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

**To Reproduce**

1. Use the action
2. Check the output of the command

### What is the current *bug* behavior

A warning appears:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Expected behavior**
No warning should appear.

**Screenshots**
<img width="735" alt="image" src="https://github.com/Cyb3r-Jak3/html5validator-action-experimental/assets/1949364/bb0ccb37-247f-4c50-9158-005322b686b8">

**Additional context**
This warning appears on any GitHub Actions configuration that you want to use.

**Comment by Cyb3r-Jak3** [comment]
This action isn't really maintained. I use it as staging for https://github.com/Cyb3r-Jak3/html5validator-action which you should be using.

**Comment by DavidePastore** [comment]
Hi @Cyb3r-Jak3. You are right. Thanks for the clarification!
